spring:
  config:
    import: optional:application-secure.yaml

  application:
    name: gsc

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.112.46:1521/db01
  jpa:
    hibernate:
      ddl-auto: update
    database: oracle
    show-sql: true

server:
  port: 8080
